Using cache found in /home/shihong/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 ðŸš€ 2023-8-28 Python-3.11.4 torch-2.0.1 CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape... 
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

  | Name            | Type       | Params
-----------------------------------------------
0 | yolov5_backbone | AutoShape  | 7.2 M 
1 | features        | Sequential | 0     
2 | regression_head | Sequential | 629 M 
3 | criterion       | MSELoss    | 0     
-----------------------------------------------
629 M     Trainable params
7.2 M     Non-trainable params
636 M     Total params
2,545.490 Total estimated model params size (MB)
SLURM auto-requeueing enabled. Setting signal handlers.
`Trainer.fit` stopped: `max_epochs=10` reached.
Traceback (most recent call last):
  File "/home/shihong/yolov5_lightning/yolov5_lightning.py", line 175, in <module>
    trainer.test(model, datamodule=data_module)
  File "/home/shihong/.conda/envs/pytorch/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 742, in test
    return call._call_and_handle_interrupt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shihong/.conda/envs/pytorch/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shihong/.conda/envs/pytorch/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 785, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shihong/.conda/envs/pytorch/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 928, in _run
    _verify_loop_configurations(self)
  File "/home/shihong/.conda/envs/pytorch/lib/python3.11/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 43, in _verify_loop_configurations
    __verify_eval_loop_configuration(model, "test")
  File "/home/shihong/.conda/envs/pytorch/lib/python3.11/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 107, in __verify_eval_loop_configuration
    raise MisconfigurationException(f"No `{step_name}()` method defined to run `Trainer.{trainer_method}`.")
lightning_fabric.utilities.exceptions.MisconfigurationException: No `test_step()` method defined to run `Trainer.test`.
